### PR TITLE
Allow concurrent use of welkin clients

### PR DESCRIPTION
**Pull request by jdiaz5513**
Without this patch any attempt to use the Welkin client concurrently will result in a file access error.

This is because of the temporary file created for auth: the `shelf` library makes no attempt to lock the file beforehand and cannot handle concurrent write access.

I added portalocker as a cross-platform way to obtain a lock (on a separate temp file) while accessing that DB file.

I've also added pytest-xdist to make sure the tests do not fail when run in parallel (they did before!).

There is one newly skipped test that fails intermittently (~1 out of 20 times). I'm not sure what to do about it, or if it is even safe to skip. We're trying to add parallelism to our own test suite so that particular issue may come to bite us anyway. It is interesting that it's only happening to a single test.

### CODE REVIEW

**Review by edcohen08 — COMMENTED** [review]
All LGTM - appreciate this change. Only thing is if you could figure out why that test is failing?

**Comment by jdiaz5513** [comment]
I can't reproduce the failing test after hundreds of test runs; looks like this is safe to merge!

**Comment by edcohen08** [comment]
Great, thank you @jdiaz5513 !

**Comment by edcohen08** [comment]
@jdiaz5513 are there cassettes that you have locally that need to be pushed up? seems like the existing cassettes are stale with this pr

**Comment by jdiaz5513** [comment]
@edcohen08 sorry that took me a bit; let's see if that fixes the packaging!

**Comment by edcohen08** [comment]
> @edcohen08 sorry that took me a bit; let's see if that fixes the packaging!
@jdiaz5513 
also have been very slow to come back to this, can you check actually it seems like the entire project packages and lock was overwritten, maybe there was an environment clash? if you could just make sure you're using the poetry.lock from dev and then only adding portalocker

**Comment by gone** [comment]
is this good to merge? it looks like the changes are pretty small

**Pull request merged**
