### PR TITLE
Bug/clean date

### PR DESCRIPTION
**Pull request by edcohen08**
This pr adds a clean date method specifically for the creation of patients with their birthdate but also general use. The clean datetime does not suffice and passing a raw date does not work with the api.

Example of failure: 
Screen Shot 2022-08-09 at 6 56 58 PM

Expected behavior is for the date to be converted into a string and the patient successfully created

### CODE REVIEW

**Review by samamorgan — COMMENTED** [review]
I had considered doing this when I first wrote the patient portion, but I don't think this is the right thing to do. Even though a person was born on a specific day, that day changes between timezones. For instance, if a person was born on May 31st in New York, that could very well be April 1st in Australia.

Best practice here would be to always pass in a timezone-aware datetime object. The `clean_datetime` method assumes that if a person passes in a timezone-naive datetime, they _meant_ to pass in a UTC timestamp.

Thoughts?

**Comment by edcohen08** [comment]
I see what you mean and largely agree but it appears Welkin doesn't even like that. Your example doesn't work to create a patient and neither does this 

`welkin.Patient(firstName="Devver", lastName="Id", birthDate="2020-12-12T00:00:00.000-04:00").create()`

 I've only seen 

`welkin.Patient(firstName="Devver", lastName="Id", birthDate="2020-12-12T00:00:00.000Z").create()` 

work. I'd gladly be wrong but I think welkin treats it as a utc standardized date.

**Comment by samamorgan** [comment]
Ahhh ok. So Welkin is defining a "DATE" object to be a ISO-8601 UTC Zulu string with a zero timestamp. That's silly

I view this as a bug in the Welkin API. A birthdate should be a full timestamp. If a doctor were to tell a patient "Happy Birthday!" but they're a few timezones away, the patient could respond with "Oh, thanks, but that was yesterday". Or maybe it doesn't matter, since the primary use of birth date is probably identity verification.

What do you think of this approach? Keeps us using the same logic for timestamp formatting regardless of input.

```python
def clean_date(date: date) -> str:
    dt = datetime(date.year, date.month, date.day, 0, 0, 0)

    return clean_datetime(dt)
```

Either way, approved, merge at your leisure.

**Review by samamorgan — APPROVED** [review]

**Comment by edcohen08** [comment]
Sweet, thank you. Opted for your method I much prefer that.

**Pull request merged**
